[workspace]
resolver = "2"
members = [
    "crates/schedule-engine",
    "crates/pack-loader",
    "crates/wallpaper-ipc",
    "crates/wallpaperctl",
    "crates/renderer",
    "crates/wallpaper-settings",
    "tools/generate-starter-pack",
]

[workspace.package]
edition = "2021"
license = "GPL-3.0-or-later"
