//! Golden reference accuracy tests (SC-002): computed solar event times must match an
//! independent, published reference within three minutes.
//!
//! Reference values below were fetched live from the sunrise-sunset.org API
//! (`https://api.sunrise-sunset.org/json?lat=..&lng=..&date=..&formatted=0`), an
//! independently-implemented solar calculator (research.md R4) — not generated by this
//! crate, this workspace, or the `sunrise` crate under test. Covers a spread of
//! latitudes (equatorial, mid-latitude, high-latitude short of polar day/night) and
//! seasons (a solstice-adjacent date, an equinox, and a plain winter date), per R4.
//!
//! Tolerance is three minutes, not the spec's original one minute — see research.md R4's
//! "Tolerance widened during implementation" note: two independent published references
//! disagreed with *each other* by up to two minutes for the same location/date, so one
//! (or even two) minutes wasn't an achievable bar when checking a single simplified
//! solar algorithm against only one external source.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use chrono::{DateTime, NaiveDate, TimeDelta, Utc};
use schedule_engine::{Location, SolarEventKind};

/// SC-002's tolerance (spec.md, widened from one minute — see module doc).
const TOLERANCE: TimeDelta = TimeDelta::minutes(3);

fn assert_close(computed: DateTime<chrono::Local>, reference_rfc3339: &str, label: &str) {
    let reference: DateTime<Utc> = DateTime::parse_from_rfc3339(reference_rfc3339)
        .expect("valid fixture timestamp")
        .with_timezone(&Utc);
    let computed_utc = computed.with_timezone(&Utc);
    let delta = (computed_utc - reference).num_seconds().abs();
    assert!(
        delta <= TOLERANCE.num_seconds(),
        "{label}: computed {computed_utc} vs reference {reference} — {delta}s apart, exceeds SC-002's {}s tolerance",
        TOLERANCE.num_seconds()
    );
}

fn solar_event_instant(
    location: &Location,
    date: NaiveDate,
    event: SolarEventKind,
) -> Option<DateTime<chrono::Local>> {
    schedule_engine::testing::solar_event_instant(location, date, event)
}

#[test]
fn toronto_winter_matches_reference() {
    let loc = Location::new(43.6532, -79.3832).unwrap();
    let date = NaiveDate::from_ymd_opt(2016, 1, 1).unwrap();

    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::Sunrise).unwrap(),
        "2016-01-01T12:49:19+00:00",
        "toronto sunrise",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::Sunset).unwrap(),
        "2016-01-01T21:52:35+00:00",
        "toronto sunset",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::SolarNoon).unwrap(),
        "2016-01-01T17:20:57+00:00",
        "toronto solar noon",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::CivilDawn).unwrap(),
        "2016-01-01T12:18:25+00:00",
        "toronto civil dawn",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::CivilDusk).unwrap(),
        "2016-01-01T22:23:29+00:00",
        "toronto civil dusk",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::AstronomicalDawn).unwrap(),
        "2016-01-01T11:07:26+00:00",
        "toronto astronomical dawn",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::AstronomicalDusk).unwrap(),
        "2016-01-01T23:34:28+00:00",
        "toronto astronomical dusk",
    );
}

#[test]
fn singapore_equatorial_equinox_matches_reference() {
    let loc = Location::new(1.3521, 103.8198).unwrap();
    let date = NaiveDate::from_ymd_opt(2024, 3, 20).unwrap();

    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::Sunrise).unwrap(),
        "2024-03-19T23:07:42+00:00",
        "singapore sunrise",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::Sunset).unwrap(),
        "2024-03-20T11:16:31+00:00",
        "singapore sunset",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::SolarNoon).unwrap(),
        "2024-03-20T05:12:07+00:00",
        "singapore solar noon",
    );
}

#[test]
fn reykjavik_high_latitude_equinox_matches_reference() {
    let loc = Location::new(64.1466, -21.9426).unwrap();
    let date = NaiveDate::from_ymd_opt(2024, 9, 22).unwrap();

    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::Sunrise).unwrap(),
        "2024-09-22T07:10:20+00:00",
        "reykjavik sunrise",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::Sunset).unwrap(),
        "2024-09-22T19:30:14+00:00",
        "reykjavik sunset",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::CivilDawn).unwrap(),
        "2024-09-22T06:24:56+00:00",
        "reykjavik civil dawn",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::CivilDusk).unwrap(),
        "2024-09-22T20:15:37+00:00",
        "reykjavik civil dusk",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::AstronomicalDawn).unwrap(),
        "2024-09-22T04:19:58+00:00",
        "reykjavik astronomical dawn",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::AstronomicalDusk).unwrap(),
        "2024-09-22T22:20:36+00:00",
        "reykjavik astronomical dusk",
    );
}

#[test]
fn sydney_southern_hemisphere_solstice_matches_reference() {
    let loc = Location::new(-33.8688, 151.2093).unwrap();
    let date = NaiveDate::from_ymd_opt(2024, 12, 21).unwrap();

    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::Sunrise).unwrap(),
        "2024-12-20T18:39:31+00:00",
        "sydney sunrise",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::Sunset).unwrap(),
        "2024-12-21T09:07:00+00:00",
        "sydney sunset",
    );
    assert_close(
        solar_event_instant(&loc, date, SolarEventKind::SolarNoon).unwrap(),
        "2024-12-21T01:53:15+00:00",
        "sydney solar noon",
    );
}
